PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS cath_pci_source_registry (source_id TEXT PRIMARY KEY,title TEXT NOT NULL,authority TEXT NOT NULL,url TEXT NOT NULL,effective_date TEXT,retrieved_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,is_primary INTEGER NOT NULL DEFAULT 1 CHECK(is_primary IN(0,1)));
CREATE TABLE IF NOT EXISTS cath_pci_policy_versions (policy_id TEXT PRIMARY KEY,engine_version TEXT NOT NULL,effective_date TEXT NOT NULL,description TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS cath_pci_code_catalog (code TEXT NOT NULL,system TEXT NOT NULL CHECK(system IN('CPT','HCPCS','ICD-10-PCS')),family TEXT NOT NULL,role TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'active',mue_value INTEGER,source_id TEXT NOT NULL REFERENCES cath_pci_source_registry(source_id),effective_date TEXT NOT NULL,PRIMARY KEY(code,system));
CREATE TABLE IF NOT EXISTS cath_pci_rule_catalog (rule_id TEXT PRIMARY KEY,policy_id TEXT NOT NULL REFERENCES cath_pci_policy_versions(policy_id),domain TEXT NOT NULL,condition_key TEXT NOT NULL,rule_summary TEXT NOT NULL,source_id TEXT NOT NULL REFERENCES cath_pci_source_registry(source_id),disposition TEXT NOT NULL CHECK(disposition IN('hold','review','allow')));
CREATE TABLE IF NOT EXISTS cath_pci_cases (case_id TEXT PRIMARY KEY,user_id TEXT NOT NULL,patient_reference TEXT,service_date TEXT,claim_scope TEXT NOT NULL,payer_type TEXT,payer_jurisdiction TEXT,status TEXT NOT NULL DEFAULT 'draft',engine_version TEXT NOT NULL,policy_version TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS cath_pci_cases_user_idx ON cath_pci_cases(user_id,created_at);
CREATE TABLE IF NOT EXISTS cath_pci_documents (document_id TEXT PRIMARY KEY,case_id TEXT NOT NULL REFERENCES cath_pci_cases(case_id) ON DELETE CASCADE,object_key TEXT,file_name TEXT NOT NULL,sha256 TEXT NOT NULL,page_count INTEGER,extraction_method TEXT,requires_manual_review INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS cath_pci_diagnostic_studies (study_id TEXT PRIMARY KEY,case_id TEXT NOT NULL REFERENCES cath_pci_cases(case_id) ON DELETE CASCADE,right_heart_state TEXT,left_heart_state TEXT,coronary_angiography_state TEXT,graft_angiography_state TEXT,complete_study_state TEXT,medical_necessity_state TEXT,prior_study_available_state TEXT,prior_study_adequate_state TEXT,changed_condition_state TEXT,inadequate_visualization_state TEXT,clinical_change_state TEXT,decision_based_on_study_state TEXT,source_document_id TEXT REFERENCES cath_pci_documents(document_id));
CREATE TABLE IF NOT EXISTS cath_pci_interventions (intervention_id TEXT PRIMARY KEY,case_id TEXT NOT NULL REFERENCES cath_pci_cases(case_id) ON DELETE CASCADE,vessel TEXT NOT NULL,artery_modifier TEXT,graft_label TEXT,lesions_treated INTEGER,stents_placed INTEGER,technique TEXT,device TEXT,approach TEXT,bifurcation_state TEXT,completed_state TEXT,source_verified_state TEXT,source_document_id TEXT REFERENCES cath_pci_documents(document_id));
CREATE TABLE IF NOT EXISTS cath_pci_adjuncts (adjunct_id TEXT PRIMARY KEY,case_id TEXT NOT NULL REFERENCES cath_pci_cases(case_id) ON DELETE CASCADE,kind TEXT NOT NULL,vessel TEXT,artery_modifier TEXT,performed_state TEXT,source_verified_state TEXT,medical_necessity_state TEXT,source_document_id TEXT REFERENCES cath_pci_documents(document_id));
CREATE TABLE IF NOT EXISTS cath_pci_diagnosis_evidence (evidence_id TEXT PRIMARY KEY,case_id TEXT NOT NULL REFERENCES cath_pci_cases(case_id) ON DELETE CASCADE,code TEXT NOT NULL,provider_documented_state TEXT NOT NULL DEFAULT 'unknown',clinically_supported_state TEXT NOT NULL DEFAULT 'unknown',source_document_id TEXT REFERENCES cath_pci_documents(document_id));
CREATE TABLE IF NOT EXISTS cath_pci_code_decisions (decision_id TEXT PRIMARY KEY,case_id TEXT NOT NULL REFERENCES cath_pci_cases(case_id) ON DELETE CASCADE,code TEXT,system TEXT NOT NULL,role TEXT NOT NULL,status TEXT NOT NULL,rationale TEXT NOT NULL,modifiers_json TEXT NOT NULL DEFAULT '[]',blockers_json TEXT NOT NULL DEFAULT '[]',units INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS cath_pci_ncci_results (result_id TEXT PRIMARY KEY,case_id TEXT NOT NULL REFERENCES cath_pci_cases(case_id) ON DELETE CASCADE,edit_version TEXT NOT NULL,code_pair TEXT NOT NULL,result_json TEXT NOT NULL,checked_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS cath_pci_approvals (approval_id TEXT PRIMARY KEY,case_id TEXT NOT NULL REFERENCES cath_pci_cases(case_id) ON DELETE CASCADE,approver_user_id TEXT NOT NULL,action TEXT NOT NULL,attestation TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS cath_pci_audit_events (event_id TEXT PRIMARY KEY,case_id TEXT REFERENCES cath_pci_cases(case_id) ON DELETE CASCADE,user_id TEXT NOT NULL,action TEXT NOT NULL,detail_json TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);

INSERT OR REPLACE INTO cath_pci_source_registry(source_id,title,authority,url,effective_date,is_primary) VALUES
('cms-pfs-rvu26c','July 2026 Medicare Physician Fee Schedule Relative Value File','CMS','https://www.cms.gov/medicare/payment/fee-schedules/physician/pfs-relative-value-files/rvu26c','2026-07-01',1),
('cms-pci-a57479','Billing and Coding: Percutaneous Coronary Interventions A57479','CMS','https://www.cms.gov/medicare-coverage-database/view/article.aspx?articleId=57479','2026-01-01',1),
('cms-cath-a52850','Billing and Coding: Cardiac Catheterization A52850','CMS','https://www.cms.gov/medicare-coverage-database/view/article.aspx?articleId=52850&ver=55','2026-01-01',1),
('cms-pci-l34761','LCD Percutaneous Coronary Interventions L34761','CMS','https://www.cms.gov/medicare-coverage-database/view/lcd.aspx?lcdid=34761&ver=34','2026-01-01',1),
('cms-cath-l33557','LCD Cardiac Catheterization L33557','CMS','https://www.cms.gov/medicare-coverage-database/view/lcd.aspx?lcdid=33557&ver=47','2026-01-01',1),
('cms-ncci-2026-xi','2026 Medicare NCCI Policy Manual Chapter XI','CMS','https://www.cms.gov/files/document/2026-ncci-medicare-policy-manual-all-chapters.pdf','2026-01-01',1),
('cms-ncci-ptp-2026q3','Medicare NCCI PTP Edits v32.2','CMS','https://www.cms.gov/medicare/coding-billing/national-correct-coding-initiative-ncci-edits/medicare-ncci-procedure-procedure-ptp-edits','2026-07-01',1),
('cms-ncci-mue-2026q3','Medicare Practitioner MUE Table','CMS','https://www.cms.gov/medicare/coding-billing/national-correct-coding-initiative-ncci-edits/medicare-ncci-medically-unlikely-edits-mues','2026-07-01',1),
('cms-ncci-aoc-2026q3','Medicare Add-on Code Edits','CMS','https://www.cms.gov/medicare/coding-billing/national-correct-coding-initiative-ncci-edits/medicare-ncci-add-code-edits','2026-07-01',1),
('cms-icd10-pcs-2026','April 2026 ICD-10-PCS Files and Guidelines','CMS','https://www.cms.gov/medicare/coding-billing/icd-10-codes','2026-04-01',1),
('cms-mcd-current','Medicare Coverage Database','CMS','https://www.cms.gov/medicare-coverage-database/search.aspx','2026-08-10',1),
('ama-cpt-current','Current Licensed CPT Guidance','AMA','https://www.ama-assn.org/practice-management/cpt','2026-01-01',1);

INSERT OR REPLACE INTO cath_pci_policy_versions(policy_id,engine_version,effective_date,description) VALUES('cath-pci-cms-2026q3','2026.08.10.1','2026-07-01','Cardiac catheterization and PCI hierarchy, lesion, vessel, diagnostic-study, PCS, NCCI, MUE, AOC, coverage, and human-review policy.');

INSERT OR REPLACE INTO cath_pci_code_catalog(code,system,family,role,status,mue_value,source_id,effective_date) VALUES
('92920','CPT','pci','angioplasty','active',3,'cms-ncci-mue-2026q3','2026-07-01'),('92924','CPT','pci','atherectomy','active',2,'cms-ncci-mue-2026q3','2026-07-01'),('92928','CPT','pci','stent-one-lesion','active',3,'cms-ncci-mue-2026q3','2026-07-01'),('92930','CPT','pci','stent-two-plus-lesions','active',1,'cms-ncci-mue-2026q3','2026-07-01'),('92933','CPT','pci','atherectomy-stent','active',2,'cms-ncci-mue-2026q3','2026-07-01'),('92937','CPT','pci','bypass-graft','active',2,'cms-ncci-mue-2026q3','2026-07-01'),('92941','CPT','pci','acute-mi-culprit','active',1,'cms-ncci-mue-2026q3','2026-07-01'),('92943','CPT','pci','cto-antegrade','active',2,'cms-ncci-mue-2026q3','2026-07-01'),('92945','CPT','pci','cto-antegrade-retrograde','active',1,'cms-ncci-mue-2026q3','2026-07-01'),
('92973','CPT','adjunct','mechanical-thrombectomy','active',2,'cms-ncci-mue-2026q3','2026-07-01'),('92974','CPT','adjunct','brachytherapy','active',1,'cms-ncci-mue-2026q3','2026-07-01'),('92978','CPT','adjunct','ivus-oct-initial','active',1,'cms-ncci-mue-2026q3','2026-07-01'),('92979','CPT','adjunct','ivus-oct-additional','active',2,'cms-ncci-mue-2026q3','2026-07-01'),('93571','CPT','adjunct','ffr-cfr-initial','active',1,'cms-ncci-mue-2026q3','2026-07-01'),('93572','CPT','adjunct','ffr-cfr-additional','active',2,'cms-ncci-mue-2026q3','2026-07-01'),
('93451','CPT','diagnostic','right-heart','active',1,'cms-ncci-mue-2026q3','2026-07-01'),('93452','CPT','diagnostic','left-heart','active',1,'cms-ncci-mue-2026q3','2026-07-01'),('93453','CPT','diagnostic','right-left-heart','active',1,'cms-ncci-mue-2026q3','2026-07-01'),('93454','CPT','diagnostic','coronary-angio','active',1,'cms-ncci-mue-2026q3','2026-07-01'),('93455','CPT','diagnostic','coronary-graft-angio','active',1,'cms-ncci-mue-2026q3','2026-07-01'),('93456','CPT','diagnostic','right-heart-coronary','active',1,'cms-ncci-mue-2026q3','2026-07-01'),('93457','CPT','diagnostic','right-heart-coronary-graft','active',1,'cms-ncci-mue-2026q3','2026-07-01'),('93458','CPT','diagnostic','left-heart-coronary','active',1,'cms-ncci-mue-2026q3','2026-07-01'),('93459','CPT','diagnostic','left-heart-coronary-graft','active',1,'cms-ncci-mue-2026q3','2026-07-01'),('93460','CPT','diagnostic','right-left-heart-coronary','active',1,'cms-ncci-mue-2026q3','2026-07-01'),('93461','CPT','diagnostic','right-left-heart-coronary-graft','active',1,'cms-ncci-mue-2026q3','2026-07-01'),
('G0269','HCPCS','facility','closure-device-packaged','bundled',NULL,'cms-pfs-rvu26c','2026-07-01'),('027034Z','ICD-10-PCS','dilation-pattern','one-coronary-des','active',NULL,'cms-icd10-pcs-2026','2026-04-01'),('02703DZ','ICD-10-PCS','dilation-pattern','one-coronary-device','active',NULL,'cms-icd10-pcs-2026','2026-04-01'),('02703ZZ','ICD-10-PCS','dilation-pattern','one-coronary-no-device','active',NULL,'cms-icd10-pcs-2026','2026-04-01'),
('92921','CPT','retired','branch-angioplasty','retired',NULL,'cms-pfs-rvu26c','2026-01-01'),('92925','CPT','retired','branch-atherectomy','retired',NULL,'cms-pfs-rvu26c','2026-01-01'),('92929','CPT','retired','branch-stent','retired',NULL,'cms-pfs-rvu26c','2026-01-01'),('92934','CPT','retired','branch-combined','retired',NULL,'cms-pfs-rvu26c','2026-01-01'),('92938','CPT','retired','branch-graft','retired',NULL,'cms-pfs-rvu26c','2026-01-01'),('92944','CPT','retired','branch-cto','retired',NULL,'cms-pfs-rvu26c','2026-01-01'),('92975','CPT','retired','thrombolysis','retired',NULL,'cms-pfs-rvu26c','2026-01-01');

INSERT OR REPLACE INTO cath_pci_rule_catalog(rule_id,policy_id,domain,condition_key,rule_summary,source_id,disposition) VALUES
('cath-inclusive-diagnostic','cath-pci-cms-2026q3','diagnostic','inclusive-family','Use one inclusive diagnostic cath family for documented components.','cms-cath-a52850','hold'),
('cath-same-session-gate','cath-pci-cms-2026q3','bundling','diagnostic-before-pci','Same-session diagnostic angiography is separate only when CMS diagnostic or justified-repeat criteria are documented.','cms-pci-a57479','hold'),
('pci-one-family-vessel','cath-pci-cms-2026q3','hierarchy','major-artery','Select one hierarchy-appropriate PCI family per major native artery or named graft.','cms-pci-a57479','hold'),
('pci-one-lesion-stent','cath-pci-cms-2026q3','lesion-count','92928','Use the current single-lesion stent family only when one treated lesion is documented.','cms-pci-a57479','hold'),
('pci-multiple-lesion-stent','cath-pci-cms-2026q3','lesion-count','92930','Use the 2026 multiple-lesion stent family only when two or more treated lesions are documented.','cms-pci-a57479','hold'),
('pci-retired-branches','cath-pci-cms-2026q3','code-status','2026-retired','Do not generate retired branch add-ons 92921, 92925, 92929, 92934, 92938, or 92944.','cms-pfs-rvu26c','hold'),
('pci-ami-one','cath-pci-cms-2026q3','mue','92941','The emergent AMI culprit intervention is limited to one unit per date of service.','cms-ncci-mue-2026q3','hold'),
('pci-cto-direction','cath-pci-cms-2026q3','technique','cto-direction','Distinguish antegrade-only CTO work from combined antegrade and retrograde work before selection.','cms-pci-a57479','hold'),
('pci-vessel-modifier','cath-pci-cms-2026q3','modifier','artery','Require source-verified LM, LD, LC, RC, or RI territory; never infer it.','cms-pci-a57479','hold'),
('pci-access-integral','cath-pci-cms-2026q3','bundling','access-imaging-closure','Access, catheter navigation, routine imaging, and closure are integral or packaged as applicable.','cms-pci-a57479','hold'),
('pci-thrombectomy','cath-pci-cms-2026q3','bundling','thrombectomy','Mechanical thrombectomy needs explicit evidence; aspiration is integral to AMI PCI and thrombectomy bundles with atherectomy.','cms-ncci-2026-xi','hold'),
('pci-adjunct-aoc','cath-pci-cms-2026q3','add-on','primary-code','Validate IVUS/OCT, physiology, thrombectomy, and brachytherapy against the current AOC file.','cms-ncci-aoc-2026q3','review'),
('pci-ncci-current','cath-pci-cms-2026q3','correct-coding','ptp-current','Check current practitioner or outpatient NCCI PTP edits for each combination.','cms-ncci-ptp-2026q3','review'),
('pci-pcs-independent','cath-pci-cms-2026q3','facility','no-cpt-crosswalk','Construct inpatient PCS independently from artery count, approach, device type/count, and bifurcation qualifier.','cms-icd10-pcs-2026','hold'),
('pci-outpatient-oce','cath-pci-cms-2026q3','facility','opps-oce','Hospital-outpatient candidates require current OPPS/OCE/APC review; do not estimate payment from professional logic.','cms-mcd-current','review'),
('pci-diagnosis-no-inference','cath-pci-cms-2026q3','diagnosis','provider-documented','Do not infer coronary disease, angina, infarction, graft disease, or complications from a procedure.','cms-ncci-2026-xi','hold'),
('pci-coverage-separate','cath-pci-cms-2026q3','coverage','payer-policy','Code selection does not establish coverage; verify date-effective payer/MAC policy and diagnosis support.','cms-mcd-current','review'),
('pci-human-release','cath-pci-cms-2026q3','safety','human-approval','Require human coder approval and disable autonomous claim submission.','cms-ncci-2026-xi','hold');
