begin;

delete from public.pgx_genes;

insert into public.pgx_genes
  (id, symbol, display_name, full_name, default_cpt, cpt_codes,
   phenotype_options, phenotype_notes, source_url, updated_at)
values
  ('cyp2d6', 'CYP2D6', 'CYP2D6', 'Cytochrome P450 Family 2 Subfamily D Member 6', '81226', '["81226","81418"]'::jsonb, '["Poor Metabolizer","Intermediate Metabolizer","Normal Metabolizer","Ultrarapid Metabolizer","Indeterminate"]'::jsonb, 'Copy-number and hybrid-allele results may affect phenotype assignment.', 'https://cpicpgx.org/genes-drugs/', now()),
  ('cyp2c19', 'CYP2C19', 'CYP2C19', 'Cytochrome P450 Family 2 Subfamily C Member 19', '81225', '["81225","81418"]'::jsonb, '["Poor Metabolizer","Intermediate Metabolizer","Normal Metabolizer","Rapid Metabolizer","Ultrarapid Metabolizer","Indeterminate"]'::jsonb, 'Phenotype translation should use the current allele-function table.', 'https://cpicpgx.org/genes-drugs/', now()),
  ('cyp2c9', 'CYP2C9', 'CYP2C9', 'Cytochrome P450 Family 2 Subfamily C Member 9', '81227', '["81227","81418"]'::jsonb, '["Poor Metabolizer","Intermediate Metabolizer","Normal Metabolizer","Indeterminate"]'::jsonb, 'Activity score and drug-specific guidance may both be required.', 'https://cpicpgx.org/genes-drugs/', now()),
  ('cyp3a5', 'CYP3A5', 'CYP3A5', 'Cytochrome P450 Family 3 Subfamily A Member 5', '81231', '["81231","81418"]'::jsonb, '["Poor Metabolizer (Non-expresser)","Intermediate Metabolizer (Expresser)","Normal Metabolizer (Expresser)","Indeterminate"]'::jsonb, 'Tacrolimus guidance distinguishes CYP3A5 expressers from non-expressers.', 'https://cpicpgx.org/genes-drugs/', now()),
  ('dpyd', 'DPYD', 'DPYD', 'Dihydropyrimidine Dehydrogenase', '81232', '["81232","81418"]'::jsonb, '["Poor Metabolizer","Intermediate Metabolizer","Normal Metabolizer","Indeterminate"]'::jsonb, 'Use the current DPYD activity-score framework and clinical guidance.', 'https://cpicpgx.org/genes-drugs/', now()),
  ('f5', 'F5', 'F5', 'Coagulation Factor V', '81241', '["81241"]'::jsonb, '["Variant Not Detected","Heterozygous Variant Detected","Homozygous Variant Detected","Indeterminate"]'::jsonb, 'This is a thrombophilia marker, not a CPIC prescribing phenotype.', 'https://www.ncbi.nlm.nih.gov/gene/2153', now()),
  ('g6pd', 'G6PD', 'G6PD', 'Glucose-6-Phosphate Dehydrogenase', '81247', '["81247","81418"]'::jsonb, '["Deficient","Intermediate","Normal","Indeterminate"]'::jsonb, 'Phenotype can depend on sex, genotype, and enzyme activity.', 'https://cpicpgx.org/genes-drugs/', now()),
  ('ifnl3', 'IFNL3', 'IFNL3', 'Interferon Lambda 3', '81283', '["81283"]'::jsonb, '["Favorable Response Genotype","Reduced Response Genotype","Indeterminate"]'::jsonb, 'Historical treatment-response marker; confirm current clinical relevance.', 'https://www.ncbi.nlm.nih.gov/gene/282617', now()),
  ('nudt15', 'NUDT15', 'NUDT15', 'Nudix Hydrolase 15', '81306', '["81306","81418"]'::jsonb, '["Poor Metabolizer","Intermediate Metabolizer","Normal Metabolizer","Indeterminate"]'::jsonb, 'Thiopurine guidance may require combined NUDT15 and TPMT results.', 'https://cpicpgx.org/genes-drugs/', now()),
  ('slco1b1', 'SLCO1B1', 'SLCO1B1', 'Solute Carrier Organic Anion Transporter Family Member 1B1', '81328', '["81328","81418"]'::jsonb, '["Poor Function","Decreased Function","Normal Function","Indeterminate"]'::jsonb, 'Use current statin-specific CPIC recommendations.', 'https://cpicpgx.org/genes-drugs/', now()),
  ('tpmt', 'TPMT', 'TPMT', 'Thiopurine S-Methyltransferase', '81335', '["81335","81418"]'::jsonb, '["Poor Metabolizer","Intermediate Metabolizer","Normal Metabolizer","Indeterminate"]'::jsonb, 'Thiopurine guidance may require combined TPMT and NUDT15 results.', 'https://cpicpgx.org/genes-drugs/', now()),
  ('ugt1a1', 'UGT1A1', 'UGT1A1', 'UDP Glucuronosyltransferase Family 1 Member A1', '81350', '["81350","81418"]'::jsonb, '["Poor Metabolizer","Intermediate Metabolizer","Normal Metabolizer","Indeterminate"]'::jsonb, 'Drug-specific guidance and the tested allele set must be reviewed.', 'https://cpicpgx.org/genes-drugs/', now()),
  ('vkorc1', 'VKORC1', 'VKORC1', 'Vitamin K Epoxide Reductase Complex Subunit 1', '81355', '["81355","81418"]'::jsonb, '["High Warfarin Sensitivity","Intermediate Warfarin Sensitivity","Typical Warfarin Sensitivity","Indeterminate"]'::jsonb, 'Interpret with CYP2C9, CYP4F2, ancestry, and clinical factors.', 'https://cpicpgx.org/genes-drugs/', now()),
  ('hla-b', 'HLA-B', 'HLA-B', 'Major Histocompatibility Complex, Class I, B', null, '["81374","81381"]'::jsonb, '["Risk Allele Positive","Risk Allele Negative","Indeterminate"]'::jsonb, 'The relevant HLA-B allele depends on the medication.', 'https://cpicpgx.org/genes-drugs/', now()),
  ('ryr1', 'RYR1', 'RYR1', 'Ryanodine Receptor 1', '81406', '["81406"]'::jsonb, '["Malignant Hyperthermia Susceptible","Uncertain Susceptibility","No Susceptibility Variant Detected"]'::jsonb, 'A negative result does not necessarily exclude malignant-hyperthermia susceptibility.', 'https://cpicpgx.org/genes-drugs/', now()),
  ('cacna1s', 'CACNA1S', 'CACNA1S', 'Calcium Voltage-Gated Channel Subunit Alpha1 S', '81479', '["81479"]'::jsonb, '["Malignant Hyperthermia Susceptible","Uncertain Susceptibility","No Susceptibility Variant Detected"]'::jsonb, 'Interpret only variants with sufficient evidence for malignant-hyperthermia susceptibility.', 'https://cpicpgx.org/genes-drugs/', now()),
  ('cyp1a2', 'CYP1A2', 'CYP1A2', 'Cytochrome P450 Family 1 Subfamily A Member 2', '81401', '["81401","81418"]'::jsonb, '["Poor Metabolizer","Intermediate Metabolizer","Normal Metabolizer","Rapid Metabolizer","Ultrarapid Metabolizer","Indeterminate"]'::jsonb, 'Smoking and interacting drugs can materially affect activity.', 'https://www.pharmgkb.org/gene/PA27093', now()),
  ('cyp2b6', 'CYP2B6', 'CYP2B6', 'Cytochrome P450 Family 2 Subfamily B Member 6', '81401', '["81401","81418"]'::jsonb, '["Poor Metabolizer","Intermediate Metabolizer","Normal Metabolizer","Rapid Metabolizer","Ultrarapid Metabolizer","Indeterminate"]'::jsonb, 'Use drug-specific phenotype translation when available.', 'https://cpicpgx.org/genes-drugs/', now()),
  ('cyp4f2', 'CYP4F2', 'CYP4F2', 'Cytochrome P450 Family 4 Subfamily F Member 2', '81401', '["81401","81418"]'::jsonb, '["Decreased Function","Normal Function","Indeterminate"]'::jsonb, 'Warfarin algorithms may incorporate CYP4F2 with other variables.', 'https://cpicpgx.org/genes-drugs/', now()),
  ('comt', 'COMT', 'COMT', 'Catechol-O-Methyltransferase', '81401', '["81401","81418"]'::jsonb, '["Low Activity","Intermediate Activity","High Activity","Indeterminate"]'::jsonb, 'No CPIC prescribing recommendation should be inferred from this phenotype alone.', 'https://www.ncbi.nlm.nih.gov/gene/1312', now()),
  ('oprm1', 'OPRM1', 'OPRM1', 'Opioid Receptor Mu 1', '81401', '["81401","81418"]'::jsonb, '["Variant Detected","Variant Not Detected","Indeterminate"]'::jsonb, 'Current opioid guidance may find insufficient evidence for a prescribing action.', 'https://cpicpgx.org/genes-drugs/', now()),
  ('cyp3a4', 'CYP3A4', 'CYP3A4', 'Cytochrome P450 Family 3 Subfamily A Member 4', '81401', '["81401","81418"]'::jsonb, '["Poor Metabolizer","Intermediate Metabolizer","Normal Metabolizer","Indeterminate"]'::jsonb, 'Phenoconversion from inhibitors or inducers must be considered.', 'https://www.pharmgkb.org/gene/PA130', now()),
  ('ugt2b15', 'UGT2B15', 'UGT2B15', 'UDP Glucuronosyltransferase Family 2 Member B15', '81401', '["81401","81418"]'::jsonb, '["Decreased Function","Normal Function","Indeterminate"]'::jsonb, 'No CPIC prescribing recommendation should be inferred unless a current guideline applies.', 'https://www.ncbi.nlm.nih.gov/gene/7366', now()),
  ('glp1r', 'GLP1R', 'GLP1R', 'Glucagon Like Peptide 1 Receptor', '81479', '["81479"]'::jsonb, '["Variant Detected","Variant Not Detected","Indeterminate"]'::jsonb, 'Research marker only; do not infer a CPIC prescribing recommendation.', 'https://www.ncbi.nlm.nih.gov/gene/2740', now());

commit;
