-- CPIC A/B pair snapshot from the CPIC API. Rows explicitly marked as
-- provisional have no implemented CPIC prescribing guideline and require
-- manual clinical review.
begin;

delete from public.pgx_gene_drug_pairs;

insert into public.pgx_gene_drug_pairs
  (id, gene, gene_symbol, drug, drug_name, drug_class, cpt_codes, cpic_level,
   fda_label_type, table_source, recommendation, source_url, updated_at)
values
  ('cyp2c19-clopidogrel','CYP2C19','CYP2C19','clopidogrel','clopidogrel','antiplatelet','["81225","81418"]','A','Actionable PGx','cpic','Use CYP2C19 phenotype and the current CPIC guideline to select antiplatelet therapy.','https://www.clinpgx.org/guideline/PA166251443',now()),
  ('cyp2c19-citalopram','CYP2C19','CYP2C19','citalopram','citalopram','SSRI','["81225","81418"]','A','Actionable PGx','cpic','Use CYP2C19 phenotype to review starting dose, titration, or an alternative SSRI.','https://www.clinpgx.org/guideline/PA166251452',now()),
  ('cyp2c19-escitalopram','CYP2C19','CYP2C19','escitalopram','escitalopram','SSRI','["81225","81418"]','A','Informative PGx','cpic','Use CYP2C19 phenotype to review starting dose, titration, or an alternative SSRI.','https://www.clinpgx.org/guideline/PA166251452',now()),
  ('cyp2c19-sertraline','CYP2C19','CYP2C19','sertraline','sertraline','SSRI','["81225","81418"]','A',null,'cpic','Use CYP2C19 phenotype with other relevant genes and clinical factors to guide dosing.','https://www.clinpgx.org/guideline/PA166251452',now()),
  ('cyp2c19-omeprazole','CYP2C19','CYP2C19','omeprazole','omeprazole','PPI','["81225","81418"]','A','Informative PGx','cpic','Use CYP2C19 phenotype and treatment indication to review PPI dose and effectiveness.','https://www.clinpgx.org/guideline/PA166251441',now()),
  ('cyp2c19-pantoprazole','CYP2C19','CYP2C19','pantoprazole','pantoprazole','PPI','["81225","81418"]','A','Actionable PGx','cpic','Use CYP2C19 phenotype and treatment indication to review PPI dose and effectiveness.','https://www.clinpgx.org/guideline/PA166251441',now()),
  ('cyp2c19-amitriptyline','CYP2C19','CYP2C19','amitriptyline','amitriptyline','TCA','["81225","81418"]','A',null,'cpic','Review CYP2C19 and CYP2D6 phenotypes together for TCA selection and dosing.','https://www.clinpgx.org/guideline/PA166251445',now()),
  ('cyp2c19-clomipramine','CYP2C19','CYP2C19','clomipramine','clomipramine','TCA','["81225","81418"]','B',null,'cpic','Review CYP2C19 and CYP2D6 phenotypes together for TCA selection and dosing.','https://www.clinpgx.org/guideline/PA166251445',now()),
  ('cyp2c9-ibuprofen','CYP2C9','CYP2C9','ibuprofen','ibuprofen','NSAID','["81227","81418"]','A',null,'cpic','Use CYP2C9 phenotype and patient risk factors to review NSAID dose and adverse-effect risk.','https://www.clinpgx.org/guideline/PA166251464',now()),
  ('cyp2c9-meloxicam','CYP2C9','CYP2C9','meloxicam','meloxicam','NSAID','["81227","81418"]','A','Informative PGx','cpic','Use CYP2C9 phenotype and patient risk factors to review NSAID dose and adverse-effect risk.','https://www.clinpgx.org/guideline/PA166251464',now()),
  ('cyp2c9-celecoxib','CYP2C9','CYP2C9','celecoxib','celecoxib','NSAID','["81227","81418"]','A','Actionable PGx','cpic','Use CYP2C9 phenotype and patient risk factors to review NSAID dose and adverse-effect risk.','https://www.clinpgx.org/guideline/PA166251464',now()),
  ('cyp2c9-phenytoin','CYP2C9','CYP2C9','phenytoin','phenytoin','anticonvulsant','["81227","81418"]','A','Actionable PGx','cpic','Use CYP2C9 phenotype with relevant HLA results and therapeutic monitoring for dosing.','https://www.clinpgx.org/guideline/PA166251461',now()),
  ('cyp2c9-warfarin','CYP2C9','CYP2C9','warfarin','warfarin','anticoagulant','["81227","81418"]','A','Actionable PGx','cpic','Use a validated pharmacogenetic dosing algorithm with CYP2C9, VKORC1, and clinical factors.','https://www.clinpgx.org/guideline/PA166251465',now()),
  ('cyp2d6-codeine','CYP2D6','CYP2D6','codeine','codeine','opioid','["81226","81418"]','A','Actionable PGx','cpic','Use CYP2D6 phenotype to assess activation, toxicity, and lack-of-effect risk before use.','https://www.clinpgx.org/guideline/PA166251454',now()),
  ('cyp2d6-tramadol','CYP2D6','CYP2D6','tramadol','tramadol','opioid','["81226","81418"]','A','Actionable PGx','cpic','Use CYP2D6 phenotype to assess activation, toxicity, and lack-of-effect risk before use.','https://www.clinpgx.org/guideline/PA166251454',now()),
  ('cyp2d6-atomoxetine','CYP2D6','CYP2D6','atomoxetine','atomoxetine','ADHD medication','["81226","81418"]','A','Actionable PGx','cpic','Use CYP2D6 phenotype and response to guide exposure-based dosing and monitoring.','https://www.clinpgx.org/guideline/PA166251459',now()),
  ('cyp2d6-tamoxifen','CYP2D6','CYP2D6','tamoxifen','tamoxifen','SERM','["81226","81418"]','A','Informative PGx','cpic','Use CYP2D6 phenotype and oncology context to review endocrine-therapy options.','https://www.clinpgx.org/guideline/PA166251458',now()),
  ('cyp2d6-venlafaxine','CYP2D6','CYP2D6','venlafaxine','venlafaxine','SNRI','["81226","81418"]','B','Informative PGx','cpic','Use CYP2D6 phenotype to review dose, monitoring, or an alternative antidepressant.','https://www.clinpgx.org/guideline/PA166251452',now()),
  ('cyp2d6-amitriptyline','CYP2D6','CYP2D6','amitriptyline','amitriptyline','TCA','["81226","81418"]','A','Informative PGx','cpic','Review CYP2D6 and CYP2C19 phenotypes together for TCA selection and dosing.','https://www.clinpgx.org/guideline/PA166251445',now()),
  ('cyp2d6-nortriptyline','CYP2D6','CYP2D6','nortriptyline','nortriptyline','TCA','["81226","81418"]','A','Informative PGx','cpic','Use CYP2D6 phenotype to review TCA starting dose, titration, and monitoring.','https://www.clinpgx.org/guideline/PA166251445',now()),
  ('cyp2d6-paroxetine','CYP2D6','CYP2D6','paroxetine','paroxetine','SSRI','["81226","81418"]','A',null,'cpic','Use CYP2D6 phenotype to review dose, titration, or an alternative SSRI.','https://www.clinpgx.org/guideline/PA166251452',now()),
  ('cyp2d6-vortioxetine','CYP2D6','CYP2D6','vortioxetine','vortioxetine','serotonin modulator','["81226","81418"]','A','Actionable PGx','cpic','Use CYP2D6 phenotype to review dose or an alternative antidepressant.','https://www.clinpgx.org/guideline/PA166251452',now()),
  ('cyp2d6-metoprolol','CYP2D6','CYP2D6','metoprolol','metoprolol','beta blocker','["81226","81418"]','B','Informative PGx','cpic','Use CYP2D6 phenotype with heart rate, blood pressure, and indication to guide therapy.','https://www.clinpgx.org/guideline/PA166343383',now()),
  ('cyp2d6-aripiprazole','CYP2D6','CYP2D6','aripiprazole','aripiprazole','antipsychotic','["81226","81418"]','B',null,'cpic','CPIC provisional pair without an implemented prescribing guideline; require manual label and clinical review.','https://api.cpicpgx.org/v1/pair_view?genesymbol=eq.CYP2D6&drugname=eq.aripiprazole',now()),
  ('cyp2d6-risperidone','CYP2D6','CYP2D6','risperidone','risperidone','antipsychotic','["81226","81418"]','B',null,'cpic','CPIC provisional pair without an implemented prescribing guideline; require manual label and clinical review.','https://api.cpicpgx.org/v1/pair_view?genesymbol=eq.CYP2D6&drugname=eq.risperidone',now()),
  ('cyp3a5-tacrolimus','CYP3A5','CYP3A5','tacrolimus','tacrolimus','immunosuppressant','["81231","81418"]','A',null,'cpic','Use CYP3A5 expresser status with therapeutic drug monitoring to guide initial dosing.','https://www.clinpgx.org/guideline/PA166251451',now()),
  ('dpyd-fluorouracil','DPYD','DPYD','fluorouracil','fluorouracil','fluoropyrimidine','["81232","81418"]','A','Testing Required','cpic','Use DPYD activity score to reduce or avoid fluoropyrimidine exposure per current guidance.','https://www.clinpgx.org/guideline/PA166251462',now()),
  ('dpyd-capecitabine','DPYD','DPYD','capecitabine','capecitabine','fluoropyrimidine','["81232","81418"]','A','Testing Required','cpic','Use DPYD activity score to reduce or avoid fluoropyrimidine exposure per current guidance.','https://www.clinpgx.org/guideline/PA166251462',now()),
  ('slco1b1-simvastatin','SLCO1B1','SLCO1B1','simvastatin','simvastatin','statin','["81328","81418"]','A',null,'cpic','Use SLCO1B1 function and statin-specific guidance to reduce muscle-symptom risk.','https://www.clinpgx.org/guideline/PA166264281',now()),
  ('slco1b1-atorvastatin','SLCO1B1','SLCO1B1','atorvastatin','atorvastatin','statin','["81328","81418"]','A',null,'cpic','Use SLCO1B1 function and statin-specific guidance to reduce muscle-symptom risk.','https://www.clinpgx.org/guideline/PA166264281',now()),
  ('slco1b1-rosuvastatin','SLCO1B1','SLCO1B1','rosuvastatin','rosuvastatin','statin','["81328","81418"]','A','Informative PGx','cpic','Use SLCO1B1 function with other relevant genes and clinical factors for statin choice.','https://www.clinpgx.org/guideline/PA166264281',now()),
  ('tpmt-azathioprine','TPMT','TPMT','azathioprine','azathioprine','thiopurine','["81335","81418"]','A','Testing Recommended','cpic','Use TPMT and NUDT15 phenotypes to select the starting dose and monitor toxicity.','https://www.clinpgx.org/guideline/PA166251442',now()),
  ('tpmt-mercaptopurine','TPMT','TPMT','mercaptopurine','mercaptopurine','thiopurine','["81335","81418"]','A','Testing Recommended','cpic','Use TPMT and NUDT15 phenotypes to select the starting dose and monitor toxicity.','https://www.clinpgx.org/guideline/PA166251442',now()),
  ('tpmt-thioguanine','TPMT','TPMT','thioguanine','thioguanine','thiopurine','["81335","81418"]','A','Testing Recommended','cpic','Use TPMT and NUDT15 phenotypes to select the starting dose and monitor toxicity.','https://www.clinpgx.org/guideline/PA166251442',now()),
  ('nudt15-azathioprine','NUDT15','NUDT15','azathioprine','azathioprine','thiopurine','["81306","81418"]','A','Testing Recommended','cpic','Use NUDT15 and TPMT phenotypes to select the starting dose and monitor toxicity.','https://www.clinpgx.org/guideline/PA166251442',now()),
  ('nudt15-mercaptopurine','NUDT15','NUDT15','mercaptopurine','mercaptopurine','thiopurine','["81306","81418"]','A','Testing Recommended','cpic','Use NUDT15 and TPMT phenotypes to select the starting dose and monitor toxicity.','https://www.clinpgx.org/guideline/PA166251442',now()),
  ('nudt15-thioguanine','NUDT15','NUDT15','thioguanine','thioguanine','thiopurine','["81306","81418"]','A','Testing Recommended','cpic','Use NUDT15 and TPMT phenotypes to select the starting dose and monitor toxicity.','https://www.clinpgx.org/guideline/PA166251442',now()),
  ('ugt1a1-atazanavir','UGT1A1','UGT1A1','atazanavir','atazanavir','antiretroviral','["81350","81418"]','A',null,'cpic','Use UGT1A1 phenotype to review bilirubin-related discontinuation risk.','https://www.clinpgx.org/guideline/PA166251453',now()),
  ('ugt1a1-irinotecan','UGT1A1','UGT1A1','irinotecan','irinotecan','topoisomerase inhibitor','["81350","81418"]','A',null,'cpic','CPIC provisional pair without an implemented prescribing guideline; require current oncology-label and clinical review.','https://api.cpicpgx.org/v1/pair_view?genesymbol=eq.UGT1A1&drugname=eq.irinotecan',now()),
  ('vkorc1-warfarin','VKORC1','VKORC1','warfarin','warfarin','anticoagulant','["81355","81418"]','A','Actionable PGx','cpic','Use a validated pharmacogenetic dosing algorithm with VKORC1, CYP2C9, and clinical factors.','https://www.clinpgx.org/guideline/PA166251465',now()),
  ('g6pd-rasburicase','G6PD','G6PD','rasburicase','rasburicase','urate oxidase','["81247","81418"]','A','Testing Required','cpic','Avoid rasburicase when G6PD deficiency is present; follow current guideline and label.','https://www.clinpgx.org/guideline/PA166251450',now()),
  ('hla-b-abacavir','HLA-B','HLA-B','abacavir','abacavir','antiretroviral','["81374","81381"]','A','Testing Required','cpic','Do not use abacavir when the relevant HLA-B risk allele is present.','https://www.clinpgx.org/guideline/PA166251444',now()),
  ('hla-b-carbamazepine','HLA-B','HLA-B','carbamazepine','carbamazepine','anticonvulsant','["81374","81381"]','A','Testing Required','cpic','Use HLA-B risk-allele status to avoid severe cutaneous adverse reactions.','https://www.clinpgx.org/guideline/PA166251448',now()),
  ('hla-b-allopurinol','HLA-B','HLA-B','allopurinol','allopurinol','urate-lowering therapy','["81374","81381"]','A','Testing Recommended','cpic','Avoid allopurinol when the relevant HLA-B risk allele is present.','https://www.clinpgx.org/guideline/PA166251446',now()),
  ('hla-b-oxcarbazepine','HLA-B','HLA-B','oxcarbazepine','oxcarbazepine','anticonvulsant','["81374","81381"]','A','Testing Recommended','cpic','Use HLA-B risk-allele status to review severe cutaneous adverse-reaction risk.','https://www.clinpgx.org/guideline/PA166251448',now()),
  ('ryr1-sevoflurane','RYR1','RYR1','sevoflurane','sevoflurane','volatile anesthetic','["81406"]','A','Actionable PGx','cpic','Avoid triggering anesthetics when malignant-hyperthermia susceptibility is established.','https://www.clinpgx.org/guideline/PA166251460',now()),
  ('cacna1s-sevoflurane','CACNA1S','CACNA1S','sevoflurane','sevoflurane','volatile anesthetic','["81479"]','A','Actionable PGx','cpic','Avoid triggering anesthetics when malignant-hyperthermia susceptibility is established.','https://www.clinpgx.org/guideline/PA166251460',now()),
  ('cyp2b6-efavirenz','CYP2B6','CYP2B6','efavirenz','efavirenz','antiretroviral','["81401","81418"]','A','Informative PGx','cpic','Use CYP2B6 phenotype to review dose, exposure, and central-nervous-system toxicity risk.','https://www.clinpgx.org/guideline/PA166251463',now()),
  ('cyp2b6-sertraline','CYP2B6','CYP2B6','sertraline','sertraline','SSRI','["81401","81418"]','B',null,'cpic','Use CYP2B6 with CYP2C19 and clinical factors when reviewing sertraline dosing.','https://www.clinpgx.org/guideline/PA166251452',now());

commit;
