/**
 * CMS ICD-10-CM 2026 Official Guidelines for Coding and Reporting
 * Source: Centers for Medicare & Medicaid Services (CMS) and NCHS
 * Published annually for the Federal Fiscal Year
 * https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines
 */

export interface GuidelineEntry {
  chapter: number;
  chapterTitle: string;
  codeRangeStart: string;
  codeRangeEnd: string;
  section: string;
  title: string;
  content: string;
  sourceUrl: string;
  tags: string[];
}

export const CMS_GUIDELINES: GuidelineEntry[] = [
  // ─── GENERAL CODING GUIDELINES ─────────────────────────────────────────────
  {
    chapter: 0,
    chapterTitle: "General Coding Guidelines",
    codeRangeStart: "A00",
    codeRangeEnd: "Z99",
    section: "II.A",
    title: "Locating a Code in the ICD-10-CM",
    content: "To select a code in the classification that corresponds to a diagnosis or reason for visit documented in a medical record, first locate the term in the Alphabetic Index, then verify the code in the Tabular List. Read and be guided by instructional notations that appear in both the Alphabetic Index and the Tabular List. It is essential to use both the Alphabetic Index and Tabular List when locating and assigning a code.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["general", "locating codes", "alphabetic index", "tabular list"],
  },
  {
    chapter: 0,
    chapterTitle: "General Coding Guidelines",
    codeRangeStart: "A00",
    codeRangeEnd: "Z99",
    section: "II.B",
    title: "Level of Detail in Coding",
    content: "Diagnosis codes are to be used and reported at their highest number of characters available. A three-character code is to be used only if it is not further subdivided. A code is invalid if it has not been coded to the full number of characters required for that code, including the 7th character, if applicable.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["general", "specificity", "code detail", "7th character"],
  },
  {
    chapter: 0,
    chapterTitle: "General Coding Guidelines",
    codeRangeStart: "A00",
    codeRangeEnd: "Z99",
    section: "II.C",
    title: "Code or Codes from A00.0 through T88.9, Z00-Z99.89",
    content: "The appropriate code or codes from A00.0 through T88.9, Z00-Z99.89 must be used to identify diagnoses, symptoms, conditions, problems, complaints or other reason(s) for the encounter/visit. Codes from A00.0 through T88.9 describe symptoms, signs, abnormal test results, or other reasons for the encounter. Z codes represent reasons for encounters and may be used in either the inpatient or outpatient setting.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["general", "code selection", "Z codes"],
  },
  {
    chapter: 0,
    chapterTitle: "General Coding Guidelines",
    codeRangeStart: "A00",
    codeRangeEnd: "Z99",
    section: "II.D",
    title: "Signs and Symptoms",
    content: "Codes that describe symptoms and signs, as opposed to diagnoses, are acceptable for reporting purposes when a related definitive diagnosis has not been established (confirmed) by the provider. The condition that is chiefly responsible for the outpatient encounter should be sequenced first. Integral signs/symptoms should not be coded separately unless instructed otherwise.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["general", "signs", "symptoms", "sequencing"],
  },
  {
    chapter: 0,
    chapterTitle: "General Coding Guidelines",
    codeRangeStart: "A00",
    codeRangeEnd: "Z99",
    section: "II.E",
    title: "Conditions that are an Integral Part of a Disease Process",
    content: "Signs and symptoms that are associated routinely with a disease process should not be assigned as additional codes, unless otherwise instructed by the classification. Codes for signs/symptoms that are routinely associated with a disease (e.g., fever with bacterial pneumonia) should not be assigned separately.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["general", "disease process", "integral signs"],
  },
  {
    chapter: 0,
    chapterTitle: "General Coding Guidelines",
    codeRangeStart: "A00",
    codeRangeEnd: "Z99",
    section: "II.J",
    title: "Laterality",
    content: "Some ICD-10-CM codes indicate laterality, specifying whether the condition occurs on the left, right or is bilateral. If no bilateral code is provided and the condition is bilateral, assign separate codes for both the left and right side. If the side is not identified in the medical record, assign the code for the unspecified side. When a patient has a bilateral condition and each side is treated during separate encounters, assign the bilateral code for the condition still present on both sides.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["general", "laterality", "bilateral", "left", "right"],
  },
  {
    chapter: 0,
    chapterTitle: "General Coding Guidelines",
    codeRangeStart: "A00",
    codeRangeEnd: "Z99",
    section: "II.K",
    title: "Documentation by Clinicians Other than the Patient's Provider",
    content: "Code assignment is based on the documentation by the patient's provider (i.e., physician or other qualified healthcare practitioner legally accountable for establishing the patient's diagnosis). Codes may be assigned based on documentation by clinicians who are not the patient's provider only for codes for Body Mass Index (BMI), depth of non-pressure chronic ulcers, pressure ulcer stage, coma scale, and NIHSS codes.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["general", "documentation", "provider", "BMI", "clinician"],
  },

  // ─── CHAPTER 1: INFECTIOUS AND PARASITIC DISEASES ─────────────────────────
  {
    chapter: 1,
    chapterTitle: "Certain Infectious and Parasitic Diseases",
    codeRangeStart: "A00",
    codeRangeEnd: "B99",
    section: "C1.a",
    title: "Human Immunodeficiency Virus (HIV) Infections — Code Selection",
    content: "Code only confirmed cases of HIV infection/illness. In this context, 'confirmation' does not require documentation of positive serology or culture for HIV; the provider's diagnostic statement that the patient is HIV positive, or has an HIV-related illness is sufficient. Select code B20, Human immunodeficiency virus [HIV] disease, when the patient has a confirmed HIV diagnosis AND is admitted for an HIV-related condition or is described as having a condition(s) resulting from HIV. In that instance the HIV disease code, B20, is sequenced first, followed by additional diagnosis codes for all reported HIV-related conditions.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["HIV", "infectious disease", "B20", "sequencing", "confirmation"],
  },
  {
    chapter: 1,
    chapterTitle: "Certain Infectious and Parasitic Diseases",
    codeRangeStart: "A00",
    codeRangeEnd: "B99",
    section: "C1.b",
    title: "HIV — Asymptomatic HIV Infection",
    content: "Code Z21, Asymptomatic human immunodeficiency virus [HIV] infection status, is to be applied when the patient without any documentation of symptoms is listed as being 'HIV positive,' 'known HIV,' 'HIV test positive,' or similar terminology. Code Z21 may also be used when the patient has an HIV infection but has not been treated for nor developed any HIV-related conditions. Do not use this code if the term 'AIDS' or 'HIV disease' is used, in which case code B20 should be assigned.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["HIV", "asymptomatic", "Z21", "B20", "AIDS"],
  },
  {
    chapter: 1,
    chapterTitle: "Certain Infectious and Parasitic Diseases",
    codeRangeStart: "A40",
    codeRangeEnd: "A41",
    section: "C1.d",
    title: "Sepsis, Severe Sepsis, and Septic Shock",
    content: "For a diagnosis of sepsis, assign the appropriate code for the underlying systemic infection. If the type of infection or causal organism is not further specified, assign code A41.9, Sepsis, unspecified organism. A code from subcategory R65.2, Severe sepsis, should also be assigned as an additional code if the medical record documentation includes that the patient has severe sepsis (i.e., sepsis with organ dysfunction). If a patient has sepsis and an associated acute organ dysfunction or multiple organ dysfunction (MOD), follow the instructions for coding severe sepsis.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["sepsis", "A41.9", "R65.2", "severe sepsis", "septic shock", "organ dysfunction"],
  },
  {
    chapter: 1,
    chapterTitle: "Certain Infectious and Parasitic Diseases",
    codeRangeStart: "A40",
    codeRangeEnd: "A41",
    section: "C1.d.1",
    title: "Septic Shock",
    content: "Septic shock generally refers to circulatory failure associated with severe sepsis, and therefore, represents a type of acute organ dysfunction. For all cases of septic shock, the code for the systemic infection should be sequenced first, followed by code R65.21, Severe sepsis with septic shock or code T81.12, Postprocedural septic shock. Any additional codes for the other acute organ dysfunctions should also be assigned. As noted in the sequencing instructions in the Tabular List, the code for septic shock cannot be assigned as a principal diagnosis.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["septic shock", "R65.21", "T81.12", "sequencing", "principal diagnosis"],
  },
  {
    chapter: 1,
    chapterTitle: "Certain Infectious and Parasitic Diseases",
    codeRangeStart: "U07",
    codeRangeEnd: "U07",
    section: "C1.h",
    title: "COVID-19 Infections",
    content: "Code U07.1, COVID-19, should be assigned for a confirmed (positive lab test) or presumptive COVID-19 diagnosis. For purposes of CMS coding, a confirmed diagnosis does not require a positive lab result; the provider's documentation of the diagnosis is sufficient. When the reason for the encounter/admission is for COVID-19, assign code U07.1 as the principal/first-listed diagnosis. For MIS-C or MIS-A associated with COVID-19, assign codes M35.81 or M35.89 plus U07.1.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["COVID-19", "U07.1", "coronavirus", "confirmed diagnosis", "MIS-C", "pandemic"],
  },

  // ─── CHAPTER 2: NEOPLASMS ─────────────────────────────────────────────────
  {
    chapter: 2,
    chapterTitle: "Neoplasms",
    codeRangeStart: "C00",
    codeRangeEnd: "D49",
    section: "C2.a",
    title: "Treatment Directed at Primary Site vs Metastatic Site",
    content: "When treatment is directed at the malignancy, designate the malignancy as the principal diagnosis. The only exception to this guideline is if a patient admission/encounter is solely for the administration of chemotherapy, immunotherapy or external beam radiation therapy, assign the appropriate Z51 code as the first-listed or principal diagnosis, and the diagnosis or problem for which the service is being performed as a secondary diagnosis.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["neoplasm", "cancer", "malignancy", "primary site", "chemotherapy", "Z51"],
  },
  {
    chapter: 2,
    chapterTitle: "Neoplasms",
    codeRangeStart: "C00",
    codeRangeEnd: "D49",
    section: "C2.b",
    title: "Neoplasm — Primary Malignancy Previously Excised",
    content: "When a primary malignancy has been previously excised or eradicated from its site and there is no further treatment directed to that site and there is no evidence of any existing primary malignancy at that site, a code from category Z85, Personal history of malignant neoplasm, should be used to indicate the former site of the malignancy. Any mention of extension, invasion, or metastasis to another site is coded as a secondary malignant neoplasm to that site.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["neoplasm", "Z85", "history", "excised", "metastasis", "secondary"],
  },
  {
    chapter: 2,
    chapterTitle: "Neoplasms",
    codeRangeStart: "C00",
    codeRangeEnd: "D49",
    section: "C2.m",
    title: "Malignant Neoplasm in a Pregnant Patient",
    content: "When a pregnant woman has a malignant neoplasm, a code from subcategory O9A.1-, Malignant neoplasm complicating pregnancy, childbirth, and the puerperium, should be sequenced first, followed by the appropriate code from Chapter 2 to indicate the type of neoplasm. Any mention of a complication associated with the malignancy should also be reported.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["neoplasm", "pregnancy", "O9A.1", "malignant", "complication"],
  },

  // ─── CHAPTER 4: ENDOCRINE ─────────────────────────────────────────────────
  {
    chapter: 4,
    chapterTitle: "Endocrine, Nutritional and Metabolic Diseases",
    codeRangeStart: "E00",
    codeRangeEnd: "E89",
    section: "C4.a",
    title: "Diabetes Mellitus — Code Assignment",
    content: "The diabetes mellitus codes are combination codes that include the type of diabetes mellitus, the body system affected, and the complications affecting that body system. As many codes within a particular category as necessary should be used to describe all of the complications of the disease. They should be sequenced based on the reason for a particular encounter. Assign as many codes from categories E08-E13 as needed to identify all of the associated conditions that the patient has.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["diabetes", "E08", "E09", "E10", "E11", "E13", "combination codes", "complications"],
  },
  {
    chapter: 4,
    chapterTitle: "Endocrine, Nutritional and Metabolic Diseases",
    codeRangeStart: "E10",
    codeRangeEnd: "E11",
    section: "C4.a.1",
    title: "Type 1 vs Type 2 Diabetes Mellitus",
    content: "Type 1 diabetes mellitus is coded to category E10, Type 1 diabetes mellitus. Type 2 diabetes mellitus is coded to category E11, Type 2 diabetes mellitus. If the documentation does not specify the type, default to type 2. Age alone is not a determining factor. If a type 2 patient uses insulin, assign an additional code from category Z79.4, Long-term (current) use of insulin, or Z79.84, Long-term (current) use of oral hypoglycemic drugs. Do not assign Z79.4 if insulin is given as a temporary measure.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["diabetes", "type 1", "type 2", "E10", "E11", "Z79.4", "insulin", "unspecified"],
  },
  {
    chapter: 4,
    chapterTitle: "Endocrine, Nutritional and Metabolic Diseases",
    codeRangeStart: "E08",
    codeRangeEnd: "E13",
    section: "C4.a.3",
    title: "Secondary Diabetes Mellitus",
    content: "Codes under categories E08, Diabetes mellitus due to underlying condition, E09, Drug or chemical induced diabetes mellitus, and E13, Other specified diabetes mellitus, identify complications/manifestations associated with secondary diabetes mellitus. Secondary diabetes is always caused by another condition or event. The sequencing of the secondary diabetes codes is based on the reason for a particular encounter. Assign as many codes from categories E08, E09, and E13 as needed.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["diabetes", "secondary diabetes", "E08", "E09", "E13", "drug-induced", "sequencing"],
  },

  // ─── CHAPTER 9: CIRCULATORY SYSTEM ────────────────────────────────────────
  {
    chapter: 9,
    chapterTitle: "Diseases of the Circulatory System",
    codeRangeStart: "I00",
    codeRangeEnd: "I99",
    section: "C9.a",
    title: "Hypertension — Coding Rules",
    content: "A causal relationship is presumed between hypertension and heart involvement and between hypertension and chronic kidney disease (CKD), whether or not the provider has documented a link between these conditions. Unless the provider specifically documents that hypertension is not related to the CKD or the heart disease, code both together. Assign codes from categories I10-I16 (hypertension), with a code from I50 (heart failure) if applicable, and with a code from N18 (CKD) if applicable.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["hypertension", "I10", "CKD", "heart failure", "I50", "N18", "causal relationship"],
  },
  {
    chapter: 9,
    chapterTitle: "Diseases of the Circulatory System",
    codeRangeStart: "I20",
    codeRangeEnd: "I25",
    section: "C9.b",
    title: "Coronary Artery Disease — CABG and Stent Coding",
    content: "ICD-10-CM has combination codes for atherosclerotic heart disease with angina pectoris. These combination codes include stenosis of native coronary arteries or bypass grafts. When using one of these combination codes it is not necessary to use an additional code for angina pectoris. A causal relationship can be assumed in a patient with both atherosclerosis and angina pectoris, unless the documentation indicates the angina is due to something other than the atherosclerosis.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["coronary artery disease", "CABG", "stent", "atherosclerosis", "angina", "I20", "I25"],
  },
  {
    chapter: 9,
    chapterTitle: "Diseases of the Circulatory System",
    codeRangeStart: "I60",
    codeRangeEnd: "I69",
    section: "C9.d",
    title: "Cerebrovascular Disease — Stroke and Sequelae Coding",
    content: "Category I69, Sequelae of cerebrovascular disease, specifies the type of stroke that caused the sequela. The neurological deficits caused by cerebrovascular disease may be present from the onset or may arise at any time after the onset of the condition. Codes from category I69 may be assigned on a health care record with codes from I60-I67 if the patient has a current CVA and a sequela of a previous CVA. Code Z86.73, Personal history of TIA, and cerebral infarction without residual deficits, should be assigned when the patient's history indicates a previous CVA.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["stroke", "CVA", "I69", "sequelae", "TIA", "cerebrovascular", "I60", "neurological deficits"],
  },
  {
    chapter: 9,
    chapterTitle: "Diseases of the Circulatory System",
    codeRangeStart: "I50",
    codeRangeEnd: "I50",
    section: "C9.f",
    title: "Heart Failure — Combination Coding and Sequencing",
    content: "Heart failure is coded with combination codes from category I50. Diastolic and systolic heart failure are classified by type and acuity. If the documentation specifies both, assign the combination code. For heart failure due to hypertension, use the I11.- (hypertensive heart disease) or I13.- (hypertensive heart and CKD disease) category codes, plus the appropriate I50 code. Code the type of heart failure if documented. If combined systolic and diastolic, assign only the combination code and not separate codes.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["heart failure", "I50", "systolic", "diastolic", "I11", "I13", "hypertension", "combination code"],
  },
  {
    chapter: 9,
    chapterTitle: "Diseases of the Circulatory System",
    codeRangeStart: "I21",
    codeRangeEnd: "I23",
    section: "C9.e",
    title: "Acute Myocardial Infarction (AMI)",
    content: "A code from category I21, Acute myocardial infarction, is used for a current AMI (defined as a 4-week timeframe). STEMIs and NSTEMIs use different subcategory codes. If a STEMI converts to NSTEMI during the same encounter, code only the STEMI. If a subsequent AMI occurs within 4 weeks, use category I22. For old or healed MIs, use code I25.2. When the MI is 28 days or less, use I21 codes. When the MI is more than 28 days old with no current symptoms, use I25.2.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["MI", "myocardial infarction", "AMI", "I21", "I22", "STEMI", "NSTEMI", "I25.2"],
  },

  // ─── CHAPTER 10: RESPIRATORY ──────────────────────────────────────────────
  {
    chapter: 10,
    chapterTitle: "Diseases of the Respiratory System",
    codeRangeStart: "J00",
    codeRangeEnd: "J99",
    section: "C10.a",
    title: "Chronic Obstructive Pulmonary Disease (COPD) and Asthma",
    content: "The codes in categories J44 and J45 distinguish between uncomplicated cases and those in acute exacerbation. An acute exacerbation is a worsening or a decompensation of a chronic condition. An acute exacerbation is not equivalent to an infection superimposed on a chronic condition, though an exacerbation may be triggered by an infection. J44 codes include COPD with/without acute exacerbation, and with/without lower respiratory infection.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["COPD", "asthma", "J44", "J45", "exacerbation", "respiratory", "infection"],
  },
  {
    chapter: 10,
    chapterTitle: "Diseases of the Respiratory System",
    codeRangeStart: "J12",
    codeRangeEnd: "J18",
    section: "C10.b",
    title: "Pneumonia — Type and Organism Coding",
    content: "When coding pneumonia, assign the specific organism code when documented. J12 is used for viral pneumonia, J13 for pneumococcal, J14 for H. influenzae, J15 for bacterial, J16 for other specified organisms, J17 for in diseases classified elsewhere, and J18 for unspecified. Do not assign J18.9 (unspecified pneumonia) if a more specific code is available. COVID-19 pneumonia is coded as U07.1 (COVID-19) first, with J12.82 as additional code.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["pneumonia", "J12", "J13", "J15", "J18", "organism", "COVID-19", "specificity"],
  },

  // ─── CHAPTER 13: MUSCULOSKELETAL ──────────────────────────────────────────
  {
    chapter: 13,
    chapterTitle: "Diseases of the Musculoskeletal System and Connective Tissue",
    codeRangeStart: "M00",
    codeRangeEnd: "M99",
    section: "C13.a",
    title: "Site and Laterality — Musculoskeletal",
    content: "Most of the codes within Chapter 13 have site and laterality designations. The site represents the bone, joint or the muscle involved. For some conditions where more than one bone, joint or muscle is usually involved, such as osteoarthritis, there is a 'multiple sites' code available. For categories where no multiple site code is provided and more than one bone, joint or muscle is involved, multiple codes should be used to indicate the different sites involved.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["musculoskeletal", "site", "laterality", "M00-M99", "bone", "joint", "muscle"],
  },
  {
    chapter: 13,
    chapterTitle: "Diseases of the Musculoskeletal System and Connective Tissue",
    codeRangeStart: "M80",
    codeRangeEnd: "M87",
    section: "C13.c",
    title: "Osteoporosis — With and Without Pathological Fractures",
    content: "Osteoporosis is a systemic condition, meaning all bones of the musculoskeletal system are affected. Therefore, site is not a component of the codes under category M81. The site codes under category M80, Osteoporosis with current pathological fracture, identify the site of the fracture, not the osteoporosis. A pathological fracture is defined as a fracture caused by disease or condition, not by trauma.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["osteoporosis", "M80", "M81", "pathological fracture", "site"],
  },

  // ─── CHAPTER 15: PREGNANCY ────────────────────────────────────────────────
  {
    chapter: 15,
    chapterTitle: "Pregnancy, Childbirth and the Puerperium",
    codeRangeStart: "O00",
    codeRangeEnd: "O9A",
    section: "C15.a",
    title: "General Rules for Obstetric Cases",
    content: "Codes from Chapter 15 are used only on the maternal record, never on the newborn record. Obstetric codes should be used for all conditions considered complicating or not normal conditions of pregnancy, delivery, and the postpartum period unless the provider documents that the pregnancy is incidental to the encounter. Chapter 15 codes have sequencing priority over codes from other chapters. Final character for trimester required. The final character designating trimester should be assigned based on the provider's documentation.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["pregnancy", "obstetric", "O00-O9A", "trimester", "maternal", "childbirth", "postpartum"],
  },
  {
    chapter: 15,
    chapterTitle: "Pregnancy, Childbirth and the Puerperium",
    codeRangeStart: "O00",
    codeRangeEnd: "O9A",
    section: "C15.b",
    title: "Supervision of Normal Pregnancy",
    content: "Codes in category Z34, Encounter for supervision of normal pregnancy, are always first listed and are not to be used with any other code from the OB chapter. Any complication of labor and delivery should be coded with the appropriate complication code. If delivery occurs during the encounter, a code from category O80 or O82 should be assigned as an additional code. The outcome of delivery code (Z37.-) should be assigned to indicate the outcome of the delivery.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["pregnancy", "normal", "Z34", "O80", "O82", "Z37", "supervision", "delivery"],
  },

  // ─── CHAPTER 19: INJURIES AND TRAUMA ─────────────────────────────────────
  {
    chapter: 19,
    chapterTitle: "Injury, Poisoning and Certain Other Consequences of External Causes",
    codeRangeStart: "S00",
    codeRangeEnd: "T88",
    section: "C19.a",
    title: "Fracture Coding — Application of 7th Characters",
    content: "A fracture not indicated as open or closed should be coded to closed. A fracture not indicated whether displaced or not displaced should be coded to displaced. ICD-10-CM requires a 7th character for most fracture categories. The 7th characters A, B, and C are for use while the patient is receiving active treatment for the fracture. 7th character D is used for fractures treated by casting. 7th character G is for fractures with delayed healing. 7th character K identifies fracture with nonunion. 7th character S identifies sequelae of the fracture.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["fracture", "7th character", "S codes", "T codes", "open", "closed", "displaced", "nonunion"],
  },
  {
    chapter: 19,
    chapterTitle: "Injury, Poisoning and Certain Other Consequences of External Causes",
    codeRangeStart: "T36",
    codeRangeEnd: "T65",
    section: "C19.e",
    title: "Poisoning vs Adverse Effect vs Underdosing",
    content: "When coding a poisoning or reaction to the improper use of a medication, the poisoning code is sequenced first, followed by the manifestation code(s). If there is also a diagnosis of drug abuse or dependence to the substance, the abuse or dependence is coded as an additional code. Adverse effects occur when a medication has been given or taken correctly; code the nature of the adverse effect first, followed by the adverse effect code. Underdosing refers to taking less of a medication than is prescribed by the provider.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["poisoning", "adverse effect", "underdosing", "T36-T65", "medication", "drug", "sequencing"],
  },
  {
    chapter: 19,
    chapterTitle: "Injury, Poisoning and Certain Other Consequences of External Causes",
    codeRangeStart: "T71",
    codeRangeEnd: "T79",
    section: "C19.g",
    title: "SIRS Due to Non-Infectious Process",
    content: "The systemic inflammatory response syndrome (SIRS) can develop as a result of certain non-infectious disease processes, such as trauma, malignant neoplasm, or pancreatitis. When SIRS is documented with a non-infectious condition, and no subsequent infection is documented, the code for the underlying condition, such as an injury, should be assigned, followed by code R65.10 or R65.11. If an associated acute organ dysfunction is documented, the appropriate code(s) for the associated acute organ dysfunction should also be assigned.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["SIRS", "R65.10", "R65.11", "non-infectious", "organ dysfunction", "trauma"],
  },

  // ─── CHAPTER 21: Z CODES ──────────────────────────────────────────────────
  {
    chapter: 21,
    chapterTitle: "Factors Influencing Health Status and Contact with Health Services",
    codeRangeStart: "Z00",
    codeRangeEnd: "Z99",
    section: "C21.a",
    title: "Z Codes — Use as Principal or First-Listed Diagnosis",
    content: "Z codes may be used as either a first-listed (principal diagnosis code in the inpatient setting) or secondary code, depending on the circumstances of the encounter. Certain Z codes may only be used as first-listed, others only as additional codes, and others may be used as either a first-listed or additional code. Z00-Z13 (Encounters for examinations) are used for general health examinations, diagnostic exams not related to specific complaints. Z codes should not be used if examination is for diagnosis of a suspected condition or if treatment is given.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["Z codes", "Z00-Z99", "first-listed", "principal diagnosis", "examinations", "health status"],
  },
  {
    chapter: 21,
    chapterTitle: "Factors Influencing Health Status and Contact with Health Services",
    codeRangeStart: "Z79",
    codeRangeEnd: "Z79",
    section: "C21.c",
    title: "Long-Term Drug Use — Z79 Codes",
    content: "Z79 codes should be assigned when a patient is receiving a medication for an extended period as a prophylactic measure (such as for the prevention of deep vein thrombosis) or as treatment of a chronic condition (such as arthritis) or a disease requiring a lengthy course of treatment. Assign Z79.4 for long-term use of insulin. Assign Z79.84 for long-term use of oral hypoglycemic drugs. Assign Z79.82 for long-term aspirin therapy. Assign Z79.01 for anticoagulants. These codes should not be assigned for medications administered for a brief period.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["Z79", "long-term", "insulin", "aspirin", "anticoagulants", "drug therapy", "chronic"],
  },
  {
    chapter: 21,
    chapterTitle: "Factors Influencing Health Status and Contact with Health Services",
    codeRangeStart: "Z87",
    codeRangeEnd: "Z87",
    section: "C21.d",
    title: "Personal History Codes — Z87 and Related",
    content: "Personal history codes explain a patient's past medical condition that no longer exists and is not receiving any treatment, but that has the potential for recurrence, and therefore may alter the treatment course. Personal history codes should be used in conjunction with follow-up codes. History codes are also used when there is no longer a current condition to code. For example, use Z85 for personal history of malignancy, Z86 for personal history of other conditions, and Z87 for personal history of other diseases.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["personal history", "Z85", "Z86", "Z87", "past medical history", "follow-up"],
  },

  // ─── REPORTING GUIDELINES ─────────────────────────────────────────────────
  {
    chapter: 0,
    chapterTitle: "Outpatient Coding and Reporting Guidelines",
    codeRangeStart: "A00",
    codeRangeEnd: "Z99",
    section: "IV.A",
    title: "Selection of First-Listed Condition (Outpatient)",
    content: "In the outpatient setting, the term 'first-listed diagnosis' is used in lieu of 'principal diagnosis.' The appropriate code(s) should be assigned to describe all diagnoses, symptoms, conditions, problems, or complaints treated or managed. The condition chiefly responsible for services provided is the first-listed diagnosis. Codes for signs and symptoms may be reported in addition to a related definitive diagnosis when the sign or symptom is not routinely associated with that diagnosis.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["outpatient", "first-listed", "principal diagnosis", "sequencing", "signs", "symptoms"],
  },
  {
    chapter: 0,
    chapterTitle: "Inpatient Coding Guidelines",
    codeRangeStart: "A00",
    codeRangeEnd: "Z99",
    section: "II.A",
    title: "Principal Diagnosis — Inpatient Selection",
    content: "The condition established after study to be chiefly responsible for occasioning the admission of the patient to the hospital for care is the principal diagnosis. In the unusual instance when two or more diagnoses equally meet the criteria for principal diagnosis, any one may be selected as principal. If the original treatment plan is not carried out, the condition that caused the original admission should still be the principal diagnosis. Coding professionals should not hesitate to query the attending provider when documentation is ambiguous.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["inpatient", "principal diagnosis", "admission", "sequencing", "attending provider"],
  },
  {
    chapter: 0,
    chapterTitle: "Inpatient Coding Guidelines",
    codeRangeStart: "A00",
    codeRangeEnd: "Z99",
    section: "III",
    title: "Reporting of Additional Diagnoses",
    content: "For reporting purposes the definition for 'other diagnoses' is interpreted as additional conditions that affect patient care in terms of requiring clinical evaluation, therapeutic treatment, diagnostic procedures, extended length of hospital stay, or increased nursing care and/or monitoring. Diagnoses that relate to an earlier episode which have no bearing on the current hospital stay are to be excluded. UHDDS definitions apply to inpatient encounters in acute care, short-term, long term care and psychiatric hospital setting.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["additional diagnoses", "inpatient", "UHDDS", "reporting", "clinical evaluation"],
  },

  // ─── CHAPTER 5: MENTAL HEALTH ─────────────────────────────────────────────
  {
    chapter: 5,
    chapterTitle: "Mental, Behavioral and Neurodevelopmental Disorders",
    codeRangeStart: "F01",
    codeRangeEnd: "F99",
    section: "C5.a",
    title: "Mental and Behavioral Disorders Due to Psychoactive Substance Use",
    content: "The codes for drug dependence and drug use are to be coded only when substance use is documented and impacts the patient's health status or current treatment. Codes for drug abuse and dependence require a 5th character, which specifies the state of the substance use (e.g., uncomplicated, in remission, with intoxication). When substance use, abuse, and dependence are documented for the same substance, assign only the dependence code. Assign the abuse code when use and abuse are both documented.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["mental health", "substance use", "F10-F19", "drug abuse", "dependence", "intoxication"],
  },

  // ─── CHAPTER 18: SYMPTOMS AND SIGNS ──────────────────────────────────────
  {
    chapter: 18,
    chapterTitle: "Symptoms, Signs and Abnormal Clinical and Laboratory Findings",
    codeRangeStart: "R00",
    codeRangeEnd: "R99",
    section: "C18.a",
    title: "Coding Uncertain Diagnoses (Inpatient)",
    content: "If the diagnosis documented at the time of discharge is qualified as 'probable', 'suspected', 'likely', 'questionable', 'possible', or 'still to be ruled out', 'compatible with', 'consistent with', or other similar terms indicating uncertainty, code the condition as if it existed or was established. These guidelines are applicable only to inpatient admissions to short-term, acute, long-term care and psychiatric hospitals. For outpatient/physician settings, code the condition to the highest degree of certainty.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/icd-10-codes/2026-icd-10-cm-guidelines",
    tags: ["uncertain diagnosis", "probable", "suspected", "inpatient", "R codes", "R00-R99"],
  },

  // ─── CPT GUIDELINES ──────────────────────────────────────────────────────
  {
    chapter: 0,
    chapterTitle: "CPT Evaluation & Management (E/M) Guidelines",
    codeRangeStart: "99202",
    codeRangeEnd: "99499",
    section: "CPT.EM.2021",
    title: "E/M 2021 Guidelines — Level Selection",
    content: "Effective January 1, 2021, the level of E/M office and outpatient visit is based on either: (1) Total time personally spent by the reporting clinician on the date of service; or (2) Medical decision making (MDM). The 1995 and 1997 examination guidelines no longer apply to outpatient E/M services. MDM is assessed in three elements: number and complexity of problems, amount and/or complexity of data reviewed, and risk of complications. All three elements of MDM must be considered when selecting the level based on MDM.",
    sourceUrl: "https://www.ama-assn.org/practice-management/cpt/changes-em-codes-2021",
    tags: ["CPT", "E/M", "evaluation", "management", "99202", "99213", "MDM", "time-based", "2021 guidelines"],
  },
  {
    chapter: 0,
    chapterTitle: "CPT Evaluation & Management (E/M) Guidelines",
    codeRangeStart: "99202",
    codeRangeEnd: "99215",
    section: "CPT.EM.NEW",
    title: "New vs Established Patient — E/M Classification",
    content: "A new patient is one who has not received any professional services from the physician/qualified health care professional or another physician/qualified health care professional of the exact same specialty and subspecialty who belongs to the same group practice, within the past 3 years. An established patient is one who has received professional services from the physician/qualified health care professional or another physician/qualified health care professional of the exact same specialty and subspecialty who belongs to the same group practice, within the past 3 years. New patient codes: 99202-99205. Established patient codes: 99211-99215.",
    sourceUrl: "https://www.ama-assn.org/practice-management/cpt/new-established-patient-guide",
    tags: ["CPT", "new patient", "established patient", "99202-99205", "99211-99215", "3-year rule"],
  },
  {
    chapter: 0,
    chapterTitle: "CPT Preventive Medicine Guidelines",
    codeRangeStart: "99381",
    codeRangeEnd: "99397",
    section: "CPT.PREV",
    title: "Preventive Medicine Services — Age-Based Coding",
    content: "Preventive medicine service codes are based on the age of the patient. Codes 99381-99387 are for new patients; 99391-99397 are for established patients. The codes are further subdivided by age: infant (<1 year), early childhood (1-4), late childhood (5-11), adolescent (12-17), 18-39, 40-64, and 65+. When medical problems are addressed at the same encounter, report an additional E/M code with modifier -25. Annual wellness visits for Medicare patients are coded differently: G0402, G0438, G0439.",
    sourceUrl: "https://www.ama-assn.org/practice-management/cpt/preventive-medicine-services",
    tags: ["preventive medicine", "wellness", "99381-99397", "age-based", "Medicare", "G0438", "G0439"],
  },

  // ─── HCPCS GUIDELINES ────────────────────────────────────────────────────
  {
    chapter: 0,
    chapterTitle: "HCPCS Level II Coding Guidelines",
    codeRangeStart: "A0000",
    codeRangeEnd: "V5364",
    section: "HCPCS.GENERAL",
    title: "HCPCS Level II — Scope and Usage",
    content: "HCPCS Level II codes are alphanumeric codes (letter A-V followed by 4 digits) developed by CMS to describe items and services not covered by CPT codes. They cover ambulance services (A codes), durable medical equipment (E codes), procedures/professional services (G codes), covered drugs (J codes), temporary non-Medicare codes (K codes), dental (D codes), and other items. HCPCS Level II codes are required for billing to Medicare and Medicaid for items and services they describe. Always verify current-year active status before using.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/healthcare-common-procedure-system",
    tags: ["HCPCS", "Level II", "DME", "ambulance", "drugs", "J codes", "G codes", "K codes"],
  },
  {
    chapter: 0,
    chapterTitle: "HCPCS Level II Coding Guidelines",
    codeRangeStart: "J0000",
    codeRangeEnd: "J9999",
    section: "HCPCS.J",
    title: "J-Codes — Drug Administration Billing",
    content: "J codes describe drugs that are administered other than oral method (e.g., injected, infused). Each J code describes a specific drug and specific unit of measure. When billing J codes, ensure the quantity billed correctly reflects the dosage administered. Use the number of units equal to the total dosage divided by the unit listed in the code descriptor. For multi-ingredient drug mixtures, each component drug should be coded separately. J3490 is used for unclassified drugs; provide the drug name and dosage in the description field.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/healthcare-common-procedure-system",
    tags: ["HCPCS", "J codes", "drugs", "injectable", "infusion", "J3490", "dosage", "units"],
  },
  {
    chapter: 0,
    chapterTitle: "HCPCS Level II Coding Guidelines",
    codeRangeStart: "E0100",
    codeRangeEnd: "E9999",
    section: "HCPCS.E",
    title: "E-Codes — Durable Medical Equipment (DME)",
    content: "E codes describe durable medical equipment (DME) including mobility aids, respiratory equipment, and hospital beds. For Medicare DME billing, medical necessity must be established with appropriate ICD-10-CM diagnosis codes. DME must meet the criteria of being durable (withstand repeated use), used for medical purpose, not useful to a person in absence of illness, and used in the home. Items coded with E codes billed to Medicare DME MACs require detailed written orders (DWO) and documentation of medical necessity.",
    sourceUrl: "https://www.cms.gov/medicare/coding-billing/healthcare-common-procedure-system",
    tags: ["HCPCS", "E codes", "DME", "durable medical equipment", "Medicare", "medical necessity", "E0100"],
  },
];
