import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const root = process.cwd();
const sourceDir = path.join(root, "server", "data", "infusion", "2026Q3");
const paymentPath = path.join(sourceDir, "cms-july-2026-part-b-payment-limits.csv");
const crosswalkPath = path.join(sourceDir, "cms-july-2026-ndc-hcpcs-crosswalk.csv");
const outputPath = path.join(root, "server", "infusion-cms-asp-data.ts");

function csvRows(value: string) {
  const rows: string[][] = [];
  let row: string[] = [];
  let field = "";
  let quoted = false;
  for (let index = 0; index < value.length; index += 1) {
    const character = value[index];
    if (quoted) {
      if (character === '"' && value[index + 1] === '"') { field += '"'; index += 1; }
      else if (character === '"') quoted = false;
      else field += character;
    } else if (character === '"') quoted = true;
    else if (character === ",") { row.push(field); field = ""; }
    else if (character === "\n") { row.push(field.replace(/\r$/, "")); rows.push(row); row = []; field = ""; }
    else field += character;
  }
  if (field || row.length) { row.push(field.replace(/\r$/, "")); rows.push(row); }
  return rows;
}

function tableFromHeader(file: string, header: string) {
  const rows = csvRows(file);
  const start = rows.findIndex((row) => row[0]?.trim() === header);
  if (start < 0) throw new Error(`Could not find ${header} header.`);
  const headers = rows[start].map((item) => item.trim());
  return rows.slice(start + 1).filter((row) => row.some((item) => item.trim())).map((row) => Object.fromEntries(headers.map((name, index) => [name, row[index]?.trim() || ""])));
}

const normalize = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
const hash = (value: Buffer) => createHash("sha256").update(value).digest("hex");
const paymentBuffer = readFileSync(paymentPath);
const crosswalkBuffer = readFileSync(crosswalkPath);
const paymentSource = paymentBuffer.toString("latin1");
const crosswalkSource = crosswalkBuffer.toString("latin1");
const paymentRows = tableFromHeader(paymentSource, "HCPCS Code");
const crosswalkRows = tableFromHeader(crosswalkSource, "_2026_CODE");

const entries = Object.fromEntries(paymentRows.map((row) => {
  const code = row["HCPCS Code"].toUpperCase();
  const parsedPayment = Number(row["Payment Limit"]);
  return [code, {
    code,
    shortDescription: row["Short Description"],
    dosageText: row["HCPCS Code Dosage"],
    paymentLimit: Number.isFinite(parsedPayment) ? parsedPayment : null,
    coinsurancePercentage: Number.isFinite(Number(row["Co-insurance Percentage"])) ? Number(row["Co-insurance Percentage"]) : null,
    pricingNote: row["Notes"] || "",
  }];
}).filter(([code]) => /^[A-Z0-9]{5}$/.test(code)));

const aliasSets = new Map<string, Set<string>>();
for (const row of crosswalkRows) {
  const code = row._2026_CODE.toUpperCase();
  const alias = normalize(row["Drug Name"]);
  if (!entries[code] || !alias) continue;
  const codes = aliasSets.get(alias) || new Set<string>();
  codes.add(code);
  aliasSets.set(alias, codes);
}
const aliases = Object.fromEntries([...aliasSets.entries()].sort(([left], [right]) => left.localeCompare(right)).map(([alias, codes]) => [alias, [...codes].sort()]));

const payload = {
  quarter: "2026Q3",
  effectiveFrom: "2026-07-01",
  effectiveTo: "2026-09-30",
  releaseDate: "2026-06-17",
  sourceHashes: { paymentLimits: hash(paymentBuffer), ndcHcpcsCrosswalk: hash(crosswalkBuffer) },
  entries,
  aliases,
};

const output = `// Generated by scripts/generate-infusion-asp-data.ts from the unmodified CMS July 2026 source files.\nexport type CmsAspDrugEntry = { code: string; shortDescription: string; dosageText: string; paymentLimit: number | null; coinsurancePercentage: number | null; pricingNote: string };\nexport const CMS_INFUSION_ASP_2026_Q3: { quarter: string; effectiveFrom: string; effectiveTo: string; releaseDate: string; sourceHashes: Record<string, string>; entries: Record<string, CmsAspDrugEntry>; aliases: Record<string, string[]> } = ${JSON.stringify(payload)};\n`;
writeFileSync(outputPath, output, "utf8");
console.log(`Generated ${outputPath} with ${Object.keys(entries).length} HCPCS entries and ${Object.keys(aliases).length} drug aliases.`);
