/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=cloudflare/workers/wrangler.public-assets.jsonc --include-runtime=false cloudflare/workers/worker-configuration.public-assets.d.ts` (hash: 8da8791dff1f5a0132bc8465f340bfd1)
interface __BaseEnv_Env {
	PUBLIC_ASSETS: R2Bucket;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./public-assets");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
