name = "codical-mcd-api"
account_id = "7dc964fd2f9e2385f0eca8850ddfc76e"
main = "mcd-api.ts"
compatibility_date = "2026-05-08"
workers_dev = true

[[d1_databases]]
binding = "MCD_DB"
database_name = "codical_mcd"
database_id = "91b644d8-174f-485b-89ee-4a59464c2141"

[[r2_buckets]]
binding = "MCD_RAW_BUCKET"
bucket_name = "codical-mcd-raw"
